# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Get flutter
        run: https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.3-stable.tar.xz

      - name: Install flutter
        run: tar -xf flutter_linux_3.24.3-stable.tar.xz -C ~

      - name: Add flutter to path
        run: echo 'export PATH="~/development/flutter/bin:$PATH"' >> ~/.bash_profile

      - name: Update
        run: sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze
